### ISSUE TITLE
How to disable TLS for presto connection

### ISSUE THREAD

**Issue by amalkurup89** [operator-framework/operator-metering#1067]

**Comment by amalkurup89** [comment]
I am trying to connect presto container, launched via operator metering from local system. I tried with the client certificates, but its throwing an exception "localhost is not a verified hostname as per certificate". So I thought of disabling tls in presto, so I can connect over http. Please let me know, how can I achieve this. I tried setting spec.tls.enabled=false in meteringconfig.yaml, but presto is launched with tls, even with this setting

**Comment by amalkurup89** [comment]
Can anyone comment on this issue

**Comment by timflannagan1** [comment]
Can you paste the `MeteringConfig` CR you used? TLS support was added in the 4.2 release cycle, so depending on what release branch you're using, specifying `tls.enabled: false` won't do much. Also, note that running Metering on pre-4.2 OCP clusters is not supported.

**Comment by amalkurup89** [comment]
I am using master branch. I will post the MeteringConfig, once I am back at office tomorrow

**Comment by amalkurup89** [comment]
PFB the contents of meteringconfig.yaml


apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      tls:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
      config:
        prometheus:
          url: 'http://prometheus-server-prometheus-grafana.apps.admcoepaas.local'
  presto:
    spec:
      tls:
        enabled: false
      coordinator:
        resources:
          limits:
            cpu: 2500m
            memory: 2Gi

      worker:
        replicas: 1
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 2000m
            memory: 2Gi
  hive:
    spec:
      tls:
        enabled: false
      metastore:
        storage:
          class: nfs-standard
          size: 1Gi
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
      server:
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
  storage:
    type: "hive"
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "metering-nfs"

**Comment by amalkurup89** [comment]
[meteringconfig.txt](https://github.com/operator-framework/operator-metering/files/4034744/meteringconfig.txt)

**Comment by amalkurup89** [comment]
@timflannagan1 Can you please comment on the above attached meteringconfig yaml file

**Comment by timflannagan1** [comment]
@amalkurup89 you can disable TLS entirely by specifying a top-level key, `spec.tls.enabled: false` instead of per-section:
```yaml
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  tls:
    enabled: false
 ...
```
Also, when you say you tried to connect to the presto container were you trying to exec into the presto-coordinator pod, e.g.
```bash
$ kubectl -n $METERING_NAMESPACE exec -it presto-coordinator-0 -c presto -- <...>
```

**Comment by timflannagan1** [comment]
I'm going to close this - feel free to re-open if you're still having issues.
