### ISSUE TITLE
No reporting operator found when install metering

### ISSUE THREAD

**Issue by xkwangcn** [operator-framework/operator-metering#1107]

**Comment by xkwangcn** [comment]
My problem:
After I run ./hack/install.sh, and use  kubectl -n $METERING_NAMESPACE get pods, I only can see:
`[root@k8s-master operator-metering]# kubectl -n $METERING_NAMESPACE get pods
NAME                                READY   STATUS    RESTARTS   AGE
metering-operator-f95c5bfbb-j8886   2/2     Running   0          7m12s`
I can't see other pod, hive-metastore-0, hive-server-0, metering-operator-df67bb6cb-6d7vh, and reporting-operator
Note:
I install the operator metering on x86 platform, and in a k8s cluster(v1.14.0);
I installed mysql, presto, hive, hadoop on the k8s master node, and these services are correct.

**Comment by xkwangcn** [comment]
export METERING_NAMESPACE=metering-$USER
export METERING_CR_FILE=/root/go/src/github.com/operator-framework/operator-metering/metering-custom.yaml
`[root@k8s-master operator-metering]# cat metering-custom.yaml 
apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  storage:
    type: hive
    # uncomment one of the hive sections below, picking one of S3, Azure, or
    # sharedPVC
    #
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "metering-nfs"
#        createPVC: true
#        storageClass: "my-nfs-storage-class"
#        size: 5Gi

  presto:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-presto
        tag: latest

  hive:
    spec:
      config:
        db:
          url: "jdbc:mysql://k8s-master:3306/metastore"
          driver: "com.mysql.cj.jdbc.Driver"
          username: "root"
          password: "mysqlpassword"
      image:
        repository: quay.io/openshift/origin-metering-hive
        tag: latest
      metastore:
        storage:
          # Default is null, which means using the default storage class if it exists.
          # If you wish to use a different storage class, specify it here
          # class: "fast-ssd"
          size: "5Gi"
  hadoop:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-hadoop
        tag: latest

  reporting-operator:
    replicas: 0
    spec:
      image:
        repository: quay.io/coreos/metering-reporting-operator
        tag: latest
        prometheus:
          url: "http://prometheus.cluster-monitoring.svc:9090"
          metricsImporter:
            auth:
              useServiceAccountToken: false
              tokenSecret:
                enabled: true
                create: true
                value: "abc-123"
      service:
        type: NodePort
        nodePort: 32313`

**Comment by xkwangcn** [comment]
now It is ok to see
```[root@k8s-master operator-metering]# kubectl get pods -n $METERING_NAMESPACE
NAME                                READY   STATUS    RESTARTS   AGE
hive-metastore-0                    0/2     Pending   0          31m
hive-server-0                       0/3     Pending   0          31m
metering-operator-f95c5bfbb-j8886   2/2     Running   0          40m
presto-coordinator-0                0/2     Pending   0          30m
# I will try to debug it for the pending pod. so I will close this issue, thank you. and if other problem, I will reopen it.

**Comment by xkwangcn** [comment]
I will try to debug it for the pending pod. so I will close this issue, thank you. and if other problem, I will reopen it.

**Comment by timflannagan1** [comment]
You specified `reporting-operator.replicas: 0` in your `MeteringConfig` custom resource file, so that makes sense why there's no reporting-operator pod being deployed.

**Comment by xkwangcn** [comment]
> You specified `reporting-operator.replicas: 0` in your `MeteringConfig` custom resource file, so that makes sense why there's no reporting-operator pod being deployed.

Wow, I will modify it and try again. Thank you very much~

May I ask you another question? 
For the pending pods above, I can see the log by `kubectl describe pod hive-server-0 -n $METERING_NAMESPACE`:
`Warning  Failed     22s (x2 over 26s)  kubelet, k8s-node3  Error: container has runAsNonRoot and image will run as root`
Could you help me to find a solution? Thank you~

**Comment by timflannagan1** [comment]
I would just install using the `./hack/upstream-install.sh` method.

**Comment by xkwangcn** [comment]
> I would just install using the `./hack/upstream-install.sh` method.

OK, thanks for your help. And I want to know what the user you used to run the `./hack/upstream-install.sh` method? is root?

**Comment by xkwangcn** [comment]
> I would just install using the `./hack/upstream-install.sh` method.

I set `runAsUser: myuserid` in my `MeteringConfig`, these pods are running now. Thank you very much.
