### ISSUE TITLE
CSV annotations can't be a list

### ISSUE THREAD

**Issue by sosiouxme** [operator-framework/operator-metering#1172]
@timflannagan1 @EmilyM1 re https://github.com/operator-framework/operator-metering/pull/1167 - this introduces an annotation as a list. That's valid yaml, but not a valid kube object - annotations are strings. We're getting validation errors downstream.

**Comment by timflannagan1** [comment]
Thanks, Luke - I got pinged about this earlier, and corrected the misalignment in [#1171](https://github.com/operator-framework/operator-metering/pull/1171)

**Comment by sosiouxme** [comment]
:+1: thanks
