### ISSUE TITLE
Documentation clarification for how ReportDataSource is handled (in metering architecture)

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-metering#279]
Hi,

operator-metering seems cool.

In the documentation of how ReportDataSource custom resource is handled (in metering-architecture.md), there are following points:

- When the custom resource is first created, if the underlying Presto table is not there, it will be created
- In the background Metering operator will scan all registered ReportDataSource resources. If any resource does not have a table created, it will skip processing that resource.

At the outset these points seem conflicting.

But my guess is following is happening. The create call will initiate table creation and will return. The background worker runs Prometheus/AWS billing query only for those ReportDataSources whose tables have been created. Is this understanding correct?

If so, the documentation can be probably tweaked a bit to make this point clearer.

**Comment by chancez** [comment]
Ah, yes that's a bit unclear, when it says it'll skip processing, I really mean that it'll skip collecting data for that datasource until the table is created.
