### ISSUE TITLE
support custom s3 endpoint

### ISSUE THREAD

**Issue by debianmaster** [operator-framework/operator-metering#423]
how can configure metering to use custom s3 endpoint (something like minio s3 storage) instead of AWS s3?

**Comment by chancez** [comment]
This isn't currently supported. Most of the work here is figuring out how well presto and hive support s3 "compatible" APIs. In my experience; most systems designed to work with S3 often don't seemlessly work with non-AWS s3 APIs and require specific client drivers for handling differences.

For example, to support Google Cloud Storage, we would likely need to use https://github.com/GoogleCloudPlatform/bigdata-interop/tree/master/gcs.

**Comment by debianmaster** [comment]
thanks for the info.   closing this for now.

**Comment by kfox1111** [comment]
Looking how to do this as well.

This site:
https://blog.minio.io/modern-data-lake-with-minio-part-2-f24fb5f82424
seems to indicate this works ok with minio, so compatibility is not an issue.

Is this configurable yet?

**Comment by chancez** [comment]
It should be possible to use these, but we would need to add configuration options to support this. This is something we're planning on adding in the near future. Most of it just exposing/setting the right configuration options in a few places. We've been laying the groundwork for this while we've started introducing Azure support (#820, #829).
