### ISSUE TITLE
metering not reporting non openshift namespaces

### ISSUE THREAD

**Issue by debianmaster** [operator-framework/operator-metering#426]
report is generated only for ocp namespaces like 
default, openshift-console, openshift-metering, openshift-sdn, openshift-web-console  but not for custom namespaces that i have created.   how do i tell metering to monitor all namespaces?

**Comment by chancez** [comment]
@debianmaster Where you able to get this working? The other thing it could be is that you don't have anything scheduled/running in non openshift namespaces, but that would be difficult I feel since openshift does run the registry and router in the default namespace.

**Comment by debianmaster** [comment]
i tested again and this does not work,  metering only reports openshift specific namespaces 
prometheus shows them all
