### ISSUE TITLE
Question: what kind of metrics are collected from operators by default?

### ISSUE THREAD

**Issue by MMarus** [operator-framework/operator-metering#474]
I am not sure if I understand the idea correctly.
Is it possible to deploy the operator-metering and it will collect metrics about all of my operators (for example etcd operator which was running even before I deployed the operator-metering)  without need to edit them?

In another words does every operator created by operator-sdk generate some metrics ?
If so what are the default metrics generated by all operators ?

Thank you very much for any answers and wish you a wonderful day :).

**Comment by chancez** [comment]
Currently we collect metrics defined by specific [Prometheus queries](https://github.com/operator-framework/operator-metering/tree/master/charts/reporting-operator/templates/custom-resources/prom-queries) and the metrics available to us is based on what your Prometheus instance is configured to monitor. We simply import metrics collected by Prometheus.

As regards to default metrics. This is something I'm working with the operator-sdk teams with on how they can produce default metrics, and make it easy to expose custom ones. We're also looking at how to then integrate with Prometheus-operator using it's ServiceMonitors to possibly have metrics automatically collected when operators are installed.

This is all stuff being planned, but not much actual real stuff has been done. That said, if your operator exposes custom Prometheus metrics, then all you need to do is get Prometheus to scrape it, and write a ReportPrometheusQuery and ReportDataSource to have metering collect the data you want. Covers this part in more detail.

**Comment by MMarus** [comment]
Thank you very much for the answer.
