### ISSUE TITLE
404 NoSuchKey error with s3 storage enabled

### ISSUE THREAD

**Issue by alinadonisa** [operator-framework/operator-metering#563]
Hi,

We have a custom installation  of operator-metering with AWS billing  enabled and storage on S3.  At first glance everything works fine except that in the logs we found a lot of 404  NoSuchKey errors accessing S3 with HeadObject method.
Troubleshooting with CloudTrail we found a lot of requests like this: 
```
aws s3api head-object --bucket mybucket --key billing/metering_health_check
aws s3api head-object --bucket mybucket --key billing/datasource_pod_request_cpu_cores/dt=2019-01-11/
aws s3api head-object --bucket mybucket --key billing/datasource_node_capacity_memory_bytes/dt=2019-01-11

...
```
Can you tell me please why this requests are made on folders from s3 and how can I fix it? 
The same request to a file located in this folders works fine. :)

The behavior it is the same for all the presto tables that are located on s3. 

Thanks,

**Comment by chancez** [comment]
Is it always failing like this, or is it just sometimes? I believe Presto does head-object to determine if it needs to create a particular directory (a table or partition).

**Comment by alinadonisa** [comment]
Yes it is Presto issue so I will close the ticket.
Thanks,
