### ISSUE TITLE
How can I enable CrossOriginResourceSharing.

### ISSUE THREAD

**Issue by JooyoungJeong** [operator-framework/operator-metering#571]
Hi. 

I need to enable "CrossOriginResourceSharing".

Is there a way to enable it by changing config?

I need help with how to handle this error.
```
Access to XMLHttpRequest at 'https://xxxxxxxxx/api/v1/reports/get?name=namespace-cpu-request-day-demo&format=json' from origin 'http://10.113.64.69:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

```

Thank you.

**Comment by chancez** [comment]
You should probably use a proxy to handle this. The API isn’t intended to be directly accessed from browsers and enabling that isn’t really something we intend to support.
