### ISSUE TITLE
How can I improve query performance.

### ISSUE THREAD

**Issue by JooyoungJeong** [operator-framework/operator-metering#582]
Hi. 

I have a lot of reports that run queries every hour.

I would like to increase the resources(cpu,memory) of presto, hive and hdfs if I try to improve the query time. Can you explain it specifically?

Currently, the number of presto's workers is zero. If I increase worker, does query time decrease?

Thank you.

**Comment by chancez** [comment]
Increasing amount of workers should help as it will increase the amount of work that can be done in parallel. However, I suggest increasing CPU and memory available first, then increasing number of worker nodes. In addition to this, HDFS and/or hive may require more resources as the number of queries running concurrently will require more connections to each of these components.

You can change the number of workers by setting `spec.presto.spec.presto.worker.replicas`. This is currently not well documented, but can be seen in https://github.com/operator-framework/operator-metering/blob/master/manifests/metering-config/recommended-resource-limits.yaml#L48-L60.

**Comment by JooyoungJeong** [comment]
@chancez 
Thank you for your reply each time.
