### ISSUE TITLE
Using kiam/kube2iam and setting annotations

### ISSUE THREAD

**Issue by jaxxstorm** [operator-framework/operator-metering#591]
I'd like to use kube2iam or kiam instead of storing credentials in secrets.

How can I set annotations on all the pods that are created by the metering-operator? I tried setting:
```
reporting-operator:
    spec:
      annotations:
```

With no success

**Comment by chancez** [comment]
I'm not near a computer with access to a cluster, so I'll have to check this tomorrow and add an example to our docs, but I believe this will set the annotations: https://gist.github.com/chancez/8ae34932c8583b9402301319b1eded33

**Comment by chancez** [comment]
Did that end up working for you?

**Comment by jaxxstorm** [comment]
Yes it did, thanks!
