### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by jaxxstorm** [operator-framework/operator-metering#682]
When calling the reporting API, I occasionally see a 504 error. This corresponds with the following log message in the reporting operator:

```
time="2019-04-15T18:46:00Z" level=error msg="failed writing HTTP response" app=metering component=api error="write tcp 192.168.201.234:8080->192.168.177.29:57608: write: broken pipe" logID=BNCvX2QBPY method=GET url="/api/v1/reports/get?name=cluster-cpu-capacity-hourly&namespace=metering&format=json"
```

Is there a way to configure the timeout for the backend reporting operator webserver?

**Comment by chancez** [comment]
I don't know that this is a timeout necessarily. This is a pretty generic write error with private network addresses. How are you querying the reporting API? If using kubectl port-forward or proxy or a loadBalancer/route can change things too.

**Comment by chancez** [comment]
Ah, it seems this is controllable by setting the `http.Server` `WriteTimeout` field. Is this something you can reproduce? Without a good way to reproduce it, this will be hard to test.

**Comment by jaxxstorm** [comment]
Yea we can reproduce this pretty easily with a large dataset. We're running behind an ingress controller which has the proxy timeout set but still getting the errors.

Ideally we could make this configurable?

**Comment by chancez** [comment]
How large is the report you're retrieving? Number of rows, etc. 

If you want to make a PR I can try to review it, but the team is currently working on some high priority tasks and won't be able to do this ourselves for a bit.

**Comment by chancez** [comment]
@jaxxstorm I'd be interested in knowing if you still see this and had any more information on this. I wouldn't be surprised if this was still an issue, but I haven't been able to hit this, even with some really long reports.

**Comment by jaxxstorm** [comment]
We moved away from operator-metering to another product, so I can't comment. Thanks for following up
