### ISSUE TITLE
OCP4.1: try to get a report from report-operator, but wrong port

### ISSUE THREAD

**Issue by rbaumgar** [operator-framework/operator-metering#759]
I try to request a report with
`https://{{hostname}}:{{port}}/api/v1/namespaces/metering/services/reporting-operator:http/proxy/api/v1/reports/get?name=pod-memory-usage&namespace=metering&format=json`

response:
```
Error: 'net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://10.129.2.26:8081/api/v1/reports/get?name=pod-memory-usage&namespace=metering&format=json'
```
reason: report-operator runs on port 8080 and not 8081!
Is their a config parameter missing?

**Comment by chancez** [comment]
How are you trying to access the reporting-operator API? This looks like you're trying to access the pod directly, but you should be using the service.

**Comment by rbaumgar** [comment]
I used postman/curl
``` 
curl -X GET \
'https://{{hostname}}:6443/api/v1/namespaces/metering/services/reporting-operator:http/proxy/api/v1/reports/get?name=pod-memory-usage&namespace=metering&format=json' \
  -H 'Authorization: Bearer xxx' \
  -H 'Postman-Token: yyy' \
  -H 'cache-control: no-cache'
```
found it at https://github.com/operator-framework/operator-metering/blob/master/Documentation/using-metering.md...
Only /api/v1/reports does not exist.

**Comment by chancez** [comment]
The URL you provided here is different from what you gave in the original comment.

You need to use `https:reporting-operator:http` within the proxy URI so the Kubernetes API proxy will connect to the service using HTTPS:

```
'https://{{hostname}}:6443/api/v1/namespaces/metering/services/https:reporting-operator:http/proxy/api/v1/reports/get?name=pod-memory-usage&namespace=metering&format=json'
```

**Comment by rbaumgar** [comment]
ok, changed. Now I get a 403 and the login screen...
Do I need somehow to setup the authentication for the proxy?

**Comment by chancez** [comment]
This is covered in https://github.com/operator-framework/operator-metering/blob/master/Documentation/configuring-reporting-operator.md#token-authentication

Take a look at https://github.com/operator-framework/operator-metering/blob/master/manifests/metering-config/advanced-auth.yaml
