### ISSUE TITLE
Support alternative storage providers (i.e. Azure, GCP) and not only S3

### ISSUE THREAD

**Issue by e9169** [operator-framework/operator-metering#774]
It would be great to have alternative storage options and not only support for S3. Something similar to Thanos' solution would be ideal.

**Comment by chancez** [comment]
@e9169 We're working on supporting Azure and GCP currently actually. I expect in the next few weeks they'll be available.

**Comment by timflannagan1** [comment]
This issue appears to never have been updated, but we added support for Azure and GCP a couple of release cycles ago. Here is a list of storage backends that metering can work with: https://docs.openshift.com/container-platform/4.3/metering/configuring_metering/metering-configure-persistent-storage.html#metering-store-data-in-azure_metering-configure-persistent-storage
