### ISSUE TITLE
Deploy with own docker images

### ISSUE THREAD

**Issue by mmariani** [operator-framework/operator-metering#804]
Hello!

I would like to try a few things, and need to build my own `ansible-operator / reporting-operator` images. I can build them with `make docker-build-all`, even in a gitlab-ci script, and serve them in my private gitlab registry.

I usually deploy the operator with `./operator-metering/hack/install.sh`. Now, can I tell him to use my images?

I tried setting `METERING_OPERATOR_IMAGE_REPO`, `METERING_OPERATOR_IMAGE_TAG`, `REPORTING_OPERATOR_IMAGE_REPO`, `REPORTING_OPERATOR_IMAGE_TAG`, `METERING_PULL_SECRET_NAME` but the mechanism to do so seems incomplete. I could hardcode the values here and there but I'd rather generalize that. Do I need Prow?

**Comment by chancez** [comment]
You can override the images in your MeteringConfig CR. I don't have comprehensive examples in the repo right now since we don't really recommend users change the image, but the `values.yaml` contains the possible values for your `MeteringConfig`'s `spec`. In there you can see all the images referenced, and update your `MeteringConfig` with the values needed.

**Comment by mmariani** [comment]
As I said above, I tried and didn't work for me, but was able (with a couple of changes) to `make run-metering-operator-local`, and from there I can customize at will.

However, it was not clear enough which values.yaml file I had to change. I ended up copying my configuration in `manifests/deploy/openshift/metering-ansible-operator/meteringconfig.yaml`.

I think I am supposed to override these values somehow instead of replacing the file, it would be nice to have it documented.

**Comment by chancez** [comment]
Like i said, you need to set the values in your `MeteringConfig` CR's spec. The documentation does cover using a custom MeteringConfig (https://github.com/operator-framework/operator-metering/blob/master/Documentation/manual-install.md#customize-installation), just there are no examples of adjusting the images. 

`make run-metering-operator-local` is intended for development and runs some stuff locally with some scripting to make that work, it isn't what you'll be wanting to use.

**Comment by mmariani** [comment]
Thanks, I ran the image locally because the upstream one was not updated for a few days, and I needed things you had fixed in the meanwhile.

> it isn't what you'll be wanting to use

I reckon it's for development/debugging, I'll use it only if I want to customize outside what's possible with the meteringconfig.yaml.
