### ISSUE TITLE
Documentation clarification for metering-architecture.md

### ISSUE THREAD

**Issue by heoneal** [operator-framework/operator-metering#923]
I noticed a puzzling difference in the PrometheusMetricsImporter and AWSBilling ReportDataSource sections of the metering-architecture.md and wanted to ask for clarity.

Is it accurate that the reporting-operator is gathering a list of ReportDataSources looking for awsBilling Rerpot while the metering operator does a similiar action?

Prometheus:
When the ReportDataSource is created, the **metering operator** does the following:

AWSBilling:

When the ReportDataSource is created, the **reporting-operator** does the following:

**Comment by heoneal** [comment]
I also believe there is a typo in the title for this section.
https://github.com/operator-framework/operator-metering/blob/master/Documentation/metering-architecture.md#reportreportqueryview-view-reportdatasources

**Comment by heoneal** [comment]
I am unclear on what is completing the actions listed in the section linked here: https://github.com/operator-framework/operator-metering/blob/master/Documentation/metering-architecture.md#report

Are the actions listed in that section completed by the metering-operator?

**Comment by chancez** [comment]
All of this is done by the reporting-operator.

**Comment by chancez** [comment]
See #924

**Comment by heoneal** [comment]
Thanks Chance! That does help clear things up. Marking closed since I see that your changes will resolve much of my confusion around metering-operator vs reporting-operator.
