### ISSUE TITLE
metering databases doesn't exist. 

### ISSUE THREAD

**Issue by jihed** [operator-framework/operator-metering#977]
I went through the troubleshooting dev guide. I see that the metering db doesn't exist in presto and hive.

`0: jdbc:hive2://127.0.0.1:10000/default> show tables from metering;
Error: Error while compiling statement: FAILED: SemanticException [Error 10072]: Database does not exist: metering (state=42000,code=10072)

34 rows selected (9.384 seconds)
0: jdbc:hive2://127.0.0.1:10000/default> show databases;
+----------------+
| database_name  |
+----------------+
| default        |
+----------------+`

**Comment by chancez** [comment]
The database `metering` was not used in 4.1, this was added in 4.2.
